# version: '3.8'

volumes:
  # db-volume:
  maildir: {}

#コンテナ詳細
services:
  nginx:
    #Webサーバーのコンテナ
    image: nginx:1.21.1
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/
    #コンテナの依存関係を示す(PHP→Nginxの順)
    depends_on:
      - php

  #phpアプリケーションのコンテナ
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/
    user: "1000:1000" # UID 1000とGID 1000の一般ユーザーとして実行

  #データベースのコンテナ
  mysql:
    image: mysql:8.0.26
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_user
      MYSQL_PASSWORD: laravel_pass
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=laravel_user
      - PMA_PASSWORD=laravel_pass
    depends_on:
      - mysql
    ports:
      - 8080:80

  #メールサーバのコンテナ
  mail:
    image: mailhog/mailhog
    # container_name: mailhog
    ports:
      - "8025:8025" # Web UI
      - "1025:1025" # SMTP
    environment:
      MH_STORAGE: maildir
      MH_MAILDIR_PATH: /tmp
    volumes:
      - maildir:/tmp
